### ISSUE TITLE
Unexpected Token

### ISSUE THREAD

**Issue by ertugruluyar-github** [Leonezz/obsidian-tasks-calendar-wrapper#4]
![image](https://user-images.githubusercontent.com/70096810/229262221-da34e5b8-9154-4594-b19e-f21f4e24bfa0.png)
![image](https://user-images.githubusercontent.com/70096810/229262233-d7f4888a-e66a-42cf-b106-6956d1806099.png)
![image](https://user-images.githubusercontent.com/70096810/229262248-9b4d2145-2f27-4290-9678-7c3d2081d054.png)

**Comment by Leonezz** [comment]
Hi, thanks for the feedback. The error indicates that there are task items which do not follow the task format, such that the parsing process went wrong.

If the ill-formated items are not meant to be a task, then this error can be ignored. Otherwise, could you please provide more details about the items? (e.g. the format, the meta data in the task item like the dates).

I try to re-produce the error in an example vault based on your screen shot, and the error does not occur, so please give me more information about what I missed. Here is what I tried:

![image](https://user-images.githubusercontent.com/33564074/229339021-7351033d-4995-4d8c-a640-8c8ae0776a01.png)

![image](https://user-images.githubusercontent.com/33564074/229339037-cb998a63-6b9b-4258-b255-387be099e1da.png)

![image](https://user-images.githubusercontent.com/33564074/229339062-0c4a7740-c489-4b19-81b0-84e65810e06a.png)

**Comment by ertugruluyar-github** [comment]
I think, ı found the parse error. Because of "- [/]"
![image](https://user-images.githubusercontent.com/70096810/229690628-8ad02491-5cf1-4d4a-a356-f6bbf861b124.png)
![image](https://user-images.githubusercontent.com/70096810/229690749-ba223af0-2097-43fe-a4b3-8dfc0db55548.png)
 I will change the settings based on your screenshot.
Before:
![image](https://user-images.githubusercontent.com/70096810/229690962-bc3dfa6a-ff1b-4cfd-b569-58592abfeb1e.png)
After:
![image](https://user-images.githubusercontent.com/70096810/229691676-f7b77d7b-69c7-4754-942b-cc8dbadac641.png)
I removed "- [/]", but still have error.
I didn't create a Inbox.md file.

This is the all file.
-----------------------
BAYYE -->This is not a header, it's file name on top of the file.
---
cssclass: research-project
file-class: _research-project_file-class
class: research-project
source-type: master-thesis
research-name: BAYYE
research-status: 7️⃣⛔ Write Intro Section
due: 2023-01-04
is-published: false
cover-image:
---
> [!info]- About

# Tasks
- [x] #task 1.Determine Research Topic 🛫 2022-11-29 📅 2022-11-30 ✅ 2022-11-30
- [x] #task 2.Literature Review 🛫 2022-12-04 📅 2022-12-22 ✅ 2022-12-25
	- [x] #task 2.1.Examine the sample papers and learn that how they do this type of research 🛫 2022-12-04 📅 2022-12-04 ✅ 2022-12-04
	- [x] #task 2.2.Examine the Prisma template and learn 🛫 2022-12-05 📅 2022-12-05 ✅ 2022-12-05
	- [x] #task 2.3.Determine Research Keywords 🛫 2022-12-06 📅 2022-12-06 ✅ 2022-12-07
	- [x] #task 2.4.Determine Selection Criteria 🛫 2022-12-12 📅 2022-12-12 ✅ 2022-12-12
	- [x] #task 2.5.Save papers to Mendeley 🛫 2022-12-13 📅 2022-12-20 ✅ 2022-12-22
		- [x] #task 2.5.1.Create Prisma's Systematic Review Flow Diagram 🛫 2022-12-15 📅 2022-12-20 ✅ 2022-12-22
		- [x] #task 2.5.2.Determine included papers by simulate the stages in the prism in the Mendeley 🛫 2022-12-13 📅 2022-12-20 ✅ 2022-12-22
	- [x] #task 2.6.In Mendeley; read papers, highlights PDFs and determine those highlights are gonna be in which research section. 🛫 2022-12-22 📅 2022-12-22 ✅ 2022-12-25
	- [x] #task 2.7.Import papers to Zotero from Mendeley 🛫 2022-12-22 📅 2022-12-22 ✅ 2022-12-25
- [x] #task 3.Write Purpose and Research Question and Sub-Research-Questions 🛫 2022-12-21 📅 2022-12-21 ✅ 2022-12-22
- [x] #task 4.Write Method Section 🛫 2022-12-12 📅 2022-12-21 ✅ 2022-12-22
- [x] #task 5.Write Findings (Results) Section 🛫 2022-12-23 📅 2022-12-24 ✅ 2022-12-29
- [ ] #task 6.Select Target Journal/Index 🛫 2022-12-24 📅 2022-12-24
- [ ] #task 7.Write Intro Section 🛫 2022-12-25 📅 2023-01-10
- [x] #task 8.Write Discussion, Conclusions and Recommendations Section 🛫 2022-12-27 📅 2022-12-28 ✅ 2023-01-03
- [x] #task 9.Write Title and Abstract Sections 🛫 2022-12-29 📅 2022-12-29 ✅ 2023-01-01
- [ ] #task 10.Write Cover Letter
- [ ] #task 11.Send To The Editor
- [ ] #task 12.Reviewing
- [ ] #task 13.Published
------------------------------------

**Comment by ertugruluyar-github** [comment]
I crated Inbox.md file and added the settings, error still happening.
![image](https://user-images.githubusercontent.com/70096810/229693713-c9a34f44-0a75-4a40-a40c-400346cc83a4.png)
![image](https://user-images.githubusercontent.com/70096810/229693784-9a04e0a2-4178-43b7-a3cd-6165cb568f89.png)

**Comment by ertugruluyar-github** [comment]
![image](https://user-images.githubusercontent.com/70096810/229694008-bc78847c-4826-4813-924a-36289fcc67ce.png)

**Comment by ertugruluyar-github** [comment]
This is my  tasks settings.
![image](https://user-images.githubusercontent.com/70096810/229694993-bec02a37-288b-457d-a320-82afc2599b65.png)

**Comment by ertugruluyar-github** [comment]
I used only Inbox file, error still happening.
![image](https://user-images.githubusercontent.com/70096810/229695376-808ac20a-d639-40fe-8ad0-40bdd1fba018.png)
![image](https://user-images.githubusercontent.com/70096810/229695418-9e57e099-d794-4278-a70e-2a7c1b8ea3dd.png)

**Comment by Leonezz** [comment]
Hi @ertugruluyar-github , thanks a lot for the information. I think I have found the issue and I will create a new release to address it asap.

**Comment by Leonezz** [comment]
@ertugruluyar-github I have released a new version (0.0.9), could you please update the plugin and confirm if the issue still exists?

**Comment by ertugruluyar-github** [comment]
I got this message sometimes.
![image](https://user-images.githubusercontent.com/70096810/229811842-85e82235-e7b9-40cd-979d-a88cbeb7d030.png)

**Comment by ertugruluyar-github** [comment]
I noticed a new issue, settings doesn't change. When I deleted the templates, it came again. 
I deleted the templates file paths then I closed the Obsidian settings and opened again, then settings doesn't change. While I'am doing this, timeline view had been open.
![image](https://user-images.githubusercontent.com/70096810/229813878-98ffb90f-e171-4806-8339-9208c845cea0.png)

**Comment by ertugruluyar-github** [comment]
I tried again but this time timeline view has been close. Then settings changed but when I open the timeline view, settings revert back again.

**Comment by ertugruluyar-github** [comment]
All my templates came in timeline view, "exclude folder" feature needed, I think.

**Comment by Leonezz** [comment]
> I got this message sometimes. ![image](https://user-images.githubusercontent.com/70096810/229811842-85e82235-e7b9-40cd-979d-a88cbeb7d030.png)

This message is shown when the sorting lambda is not valid, you can empty it on the setting page.
Actually, I personally never use this feature, so I am wondering whether it is needed as an option.

**Comment by Leonezz** [comment]
> I noticed a new issue, settings doesn't change. When I deleted the templates, it came again. I deleted the templates file paths then I closed the Obsidian settings and opened again, then settings doesn't change. While I'am doing this, timeline view had been open. ![image](https://user-images.githubusercontent.com/70096810/229813878-98ffb90f-e171-4806-8339-9208c845cea0.png)

Thanks for the report, I will resolve this in the next release.

**Comment by Leonezz** [comment]
> All my templates came in timeline view, "exclude folder" feature needed, I think.

I think it is good advice, will add it in the next release.
I personally like to organize notes based on tags, but folder-based should be also applicable.

**Comment by Leonezz** [comment]
Hi @ertugruluyar-github , with the latest release, now the issue is resolved and the exclude folder feature is now available.
